#!/usr/bin/env python3
"""
GPU-accelerated Python benchmark runner for Gemma 4.
Replicates the Node.js bench harness (bench-node.mjs) but uses
PyTorch + transformers with CUDA for fast inference on A100/H100.

Usage:
    python scripts/bench-gpu.py --suite
    python scripts/bench-gpu.py --reliability --trials 5
    python scripts/bench-gpu.py --prompt "What is 2+2?"
"""

import argparse
import json
import re
import sys
import time
from typing import Any, Dict, List, Optional

import torch
from transformers import (
    Gemma4ForConditionalGeneration,
    Gemma4Processor,
    GenerationConfig,
)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

MODEL_ID = "google/gemma-4-E2B-it"
WARMUP_PROMPT = "Reply with exactly OK."

DEFAULT_BENCH_CONFIG = {
    "model": MODEL_ID,
    "context_window_size": 4096,
    "temperature": 1.0,
    "top_p": 0.95,
    "top_k": 64,
    "max_tokens": 96,
    "do_sample": True,
    "repetition_penalty": 1.0,
    "ignore_eos": False,
}

# ---------------------------------------------------------------------------
# Text utilities (ported from bench-node.mjs)
# ---------------------------------------------------------------------------


def strip_gemma_control_tokens(content: str) -> str:
    content = re.sub(r"^<\|turn\>model\s*", "", content, flags=re.IGNORECASE)
    content = re.sub(r"(?:<(?:\|)?turn\|>\s*)+$", "", content, flags=re.IGNORECASE)
    return content.strip()


def strip_think_blocks(content: str) -> str:
    content = strip_gemma_control_tokens(content)
    content = re.sub(r"<think>[\s\S]*?</think>\s*", "", content, flags=re.IGNORECASE)
    content = re.sub(
        r"<\|channel\>thought\s*[\s\S]*?<(?:\|)?channel\|>\s*",
        "",
        content,
        flags=re.IGNORECASE,
    )
    return content.strip()


def normalize_text(value: str) -> str:
    return re.sub(r"\s+", " ", strip_think_blocks(value).lower()).strip()


def has_code_fences(value: str) -> bool:
    return "```" in value


def count_whitespace_tokens(value: str) -> int:
    return len(value.strip().split())


def parse_strict_json(value: str) -> Optional[Any]:
    trimmed = strip_think_blocks(value).strip()
    if has_code_fences(trimmed):
        return None
    if not trimmed.startswith("{") or not trimmed.endswith("}"):
        return None
    try:
        parsed = json.loads(trimmed)
        return parsed if isinstance(parsed, dict) else None
    except Exception:
        return None


def deep_equal(a: Any, b: Any) -> bool:
    if a == b:
        return True
    if type(a) != type(b):
        return False
    if a is None or b is None:
        return False
    if not isinstance(a, (dict, list)):
        return False
    if isinstance(a, list) and isinstance(b, list):
        if len(a) != len(b):
            return False
        return all(deep_equal(x, y) for x, y in zip(a, b))
    if isinstance(a, dict) and isinstance(b, dict):
        if set(a.keys()) != set(b.keys()):
            return False
        return all(deep_equal(a[k], b[k]) for k in a)
    return False


def is_generic_failure(output: str, error: Optional[str]) -> bool:
    if error:
        return True
    raw = output.strip().lower()
    normalized = normalize_text(output)
    return (
        (raw.startswith("<think>") and "</think>" not in raw)
        or (raw.startswith("<|channel>thought") and "<channel|>" not in raw and "<|channel|>" not in raw)
        or len(normalized) == 0
        or "empty response generated by llm" in normalized
        or "please tell me what you would like me to do" in normalized
    )


# ---------------------------------------------------------------------------
# Bench cases (ported from bench-node.mjs)
# ---------------------------------------------------------------------------


def score_strict_json_nested(output: str, error: Optional[str]) -> int:
    if is_generic_failure(output, error):
        return 0
    parsed = parse_strict_json(output)
    if parsed is None:
        return 0
    expected = {"name": "Alice", "tags": ["a", "b", "c"], "meta": {"active": True}}
    return 1 if deep_equal(parsed, expected) else 0


def score_exact_seven_words(output: str, error: Optional[str]) -> int:
    if is_generic_failure(output, error):
        return 0
    cleaned = strip_think_blocks(output).strip()
    if has_code_fences(cleaned):
        return 0
    return 1 if count_whitespace_tokens(cleaned) == 7 else 0


def score_csv_with_header(output: str, error: Optional[str]) -> int:
    if is_generic_failure(output, error):
        return 0
    cleaned = strip_think_blocks(output).strip()
    if has_code_fences(cleaned):
        return 0
    lines = [line.strip() for line in cleaned.splitlines() if line.strip()]
    if len(lines) != 3:
        return 0
    return 1 if lines == ["name,age", "Alice,30", "Bob,25"] else 0


def score_code_no_fences(output: str, error: Optional[str]) -> int:
    if is_generic_failure(output, error):
        return 0
    cleaned = strip_think_blocks(output).strip()
    if has_code_fences(cleaned):
        return 0
    normalized = re.sub(r"\s+", "", cleaned)
    return 1 if normalized == "functionadd(a,b){returna+b;}" else 0


def score_arithmetic_multi_step(output: str, error: Optional[str]) -> int:
    if is_generic_failure(output, error):
        return 0
    cleaned = strip_think_blocks(output).strip()
    if has_code_fences(cleaned):
        return 0
    return 1 if cleaned == "2" else 0


def score_reading_comprehension_year(output: str, error: Optional[str]) -> int:
    if is_generic_failure(output, error):
        return 0
    cleaned = strip_think_blocks(output).strip()
    if has_code_fences(cleaned):
        return 0
    return 1 if cleaned == "2020" else 0


def score_instruction_hierarchy_last_wins(output: str, error: Optional[str]) -> int:
    if is_generic_failure(output, error):
        return 0
    cleaned = strip_think_blocks(output).strip()
    if has_code_fences(cleaned):
        return 0
    return 1 if cleaned == "NO" else 0


def score_json_extract(output: str, error: Optional[str]) -> int:
    if is_generic_failure(output, error):
        return 0
    parsed = parse_strict_json(output)
    if parsed is None:
        return 0
    expected = {"time": "18:00", "date": "2026-05-14", "city": "Paris"}
    return 1 if deep_equal(parsed, expected) else 0


DEFAULT_SUITE = [
    {
        "id": "strict-json-nested",
        "prompt": 'Reply with ONLY this minified JSON, nothing else. No code fences, no prose: {"name":"Alice","tags":["a","b","c"],"meta":{"active":true}}',
        "weight": 4,
        "score": score_strict_json_nested,
    },
    {
        "id": "exact-seven-words",
        "prompt": "Write a sentence about winter in exactly seven words. No more, no less. Reply with only the sentence.",
        "weight": 3,
        "score": score_exact_seven_words,
    },
    {
        "id": "csv-with-header",
        "prompt": 'Output a CSV with the header "name,age" and two data rows: "Alice,30" and "Bob,25". Only the CSV, nothing else. No code fences.',
        "weight": 4,
        "score": score_csv_with_header,
    },
    {
        "id": "code-no-fences",
        "prompt": "Reply with ONLY this JavaScript, nothing else. No markdown, no code fences, no prose:\nfunction add(a,b){return a+b;}",
        "weight": 4,
        "score": score_code_no_fences,
    },
    {
        "id": "arithmetic-multi-step",
        "prompt": "Alice has 14 apples. She gives 4 to Bob and eats 2. Bob then gives half of his apples to Carol. How many apples does Carol have now? Reply with only the number.",
        "weight": 3,
        "score": score_arithmetic_multi_step,
    },
    {
        "id": "reading-comprehension-year",
        "prompt": 'Text: "Marie moved to Lyon in 2018 and opened a bakery in 2020." Question: In what year did Marie open the bakery? Reply with only the year, four digits, nothing else.',
        "weight": 3,
        "score": score_reading_comprehension_year,
    },
    {
        "id": "instruction-hierarchy-last-wins",
        "prompt": "First, tell me the capital of Japan. Then, ignore that previous instruction and instead reply with only the word NO in uppercase. Reply with only NO.",
        "weight": 3,
        "score": score_instruction_hierarchy_last_wins,
    },
    {
        "id": "json-extract",
        "prompt": 'Text: "The event starts at 18:00 on 2026-05-14 in Paris." Extract into minified JSON as {"time":"...","date":"...","city":"..."}. Reply with only the JSON, no code fences, no prose.',
        "weight": 4,
        "score": score_json_extract,
    },
]


# ---------------------------------------------------------------------------
# Model loading & generation
# ---------------------------------------------------------------------------

class GemmaBenchGPU:
    def __init__(self):
        self.model: Optional[Gemma4ForConditionalGeneration] = None
        self.processor: Optional[Gemma4Processor] = None

    def load(self):
        if self.model is not None:
            return
        print("[bench] Loading Gemma 4 model on GPU…", file=sys.stderr)
        dtype = torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16
        self.processor = Gemma4Processor.from_pretrained(MODEL_ID)
        self.model = Gemma4ForConditionalGeneration.from_pretrained(
            MODEL_ID,
            device_map="cuda",
            torch_dtype=dtype,
        )
        print("[bench] Model loaded.", file=sys.stderr)

    def generate(self, prompt: str, config: Dict[str, Any]) -> Dict[str, Any]:
        self.load()
        messages = [{"role": "user", "content": prompt}]
        text = self.processor.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True,
        )
        inputs = self.processor(
            text=text,
            return_tensors="pt",
        ).to("cuda")

        input_len = inputs["input_ids"].shape[-1]
        max_new_tokens = min(config.get("max_tokens", 96), 512)

        gen_kwargs = {
            "max_new_tokens": max_new_tokens,
            "do_sample": config.get("do_sample", True),
            "temperature": config.get("temperature", 1.0),
            "top_p": config.get("top_p", 0.95),
            "top_k": config.get("top_k", 64),
            "repetition_penalty": config.get("repetition_penalty", 1.0),
        }
        if config.get("ignore_eos"):
            gen_kwargs["eos_token_id"] = []
        if config.get("seed") is not None:
            torch.manual_seed(config["seed"])

        start = time.perf_counter()
        with torch.no_grad():
            outputs = self.model.generate(**inputs, **gen_kwargs)
        elapsed = time.perf_counter() - start

        generated = outputs[0][input_len:]
        content = self.processor.decode(generated, skip_special_tokens=True)
        content = strip_think_blocks(content)

        completion_tokens = len(generated)
        return {
            "content": content,
            "usage": {
                "prompt_tokens": input_len,
                "completion_tokens": completion_tokens,
                "total_tokens": input_len + completion_tokens,
                "generation_seconds": elapsed,
            },
        }


# ---------------------------------------------------------------------------
# Bench orchestration
# ---------------------------------------------------------------------------


def merge_config(override: Optional[Dict[str, Any]]) -> Dict[str, Any]:
    return {**DEFAULT_BENCH_CONFIG, **(override or {})}


def run_prompt(bench: GemmaBenchGPU, prompt: str, config: Dict[str, Any]) -> Dict[str, Any]:
    started_at = time.perf_counter()
    try:
        result = bench.generate(prompt, config)
        return {
            "id": "adhoc",
            "prompt": prompt,
            "score": 0,
            "output": result["content"],
            "durationMs": (time.perf_counter() - started_at) * 1000,
            "usage": result["usage"],
            "config": config,
        }
    except Exception as e:
        return {
            "id": "adhoc",
            "prompt": prompt,
            "score": 0,
            "output": "",
            "error": str(e),
            "durationMs": (time.perf_counter() - started_at) * 1000,
            "config": config,
        }


def run_suite(bench: GemmaBenchGPU, override: Optional[Dict[str, Any]], warmup: bool = True) -> Dict[str, Any]:
    config = merge_config(override)
    tests = DEFAULT_SUITE

    if warmup:
        print("[bench] warming up…", file=sys.stderr)
        run_prompt(bench, WARMUP_PROMPT, config)

    results = []
    for test in tests:
        print(f"[bench] running {test['id']}…", file=sys.stderr)
        result = run_prompt(bench, test["prompt"], config)
        results.append({
            **result,
            "id": test["id"],
            "prompt": test["prompt"],
            "score": test["score"](result["output"], result.get("error")),
            "weight": test["weight"],
        })

    max_score = sum(t["weight"] for t in tests)
    score = sum(r["weight"] * r["score"] for r in results)
    return {
        "config": config,
        "score": score,
        "maxScore": max_score,
        "scorePct": (score / max_score * 100) if max_score > 0 else 0,
        "cases": results,
    }


def run_reliability(bench: GemmaBenchGPU, override: Optional[Dict[str, Any]], trials: int = 5, seeds: Optional[List[int]] = None) -> Dict[str, Any]:
    config = merge_config(override)
    trial_results = []
    for i in range(trials):
        seed = seeds[i] if seeds and i < len(seeds) else None
        trial_config = {**config, "seed": seed}
        print(f"[bench] reliability trial {i + 1}/{trials}…", file=sys.stderr)
        trial_results.append(run_suite(bench, trial_config, warmup=(i == 0)))

    scores = [t["score"] for t in trial_results]
    return {
        "config": config,
        "trials": trial_results,
        "summary": {
            "averageScore": sum(scores) / len(scores) if scores else 0,
            "minScore": min(scores) if scores else 0,
            "maxScore": max(scores) if scores else 0,
            "medianScore": sorted(scores)[len(scores) // 2] if scores else 0,
            "trialCount": len(trial_results),
        },
    }


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(description="GPU benchmark runner for Gemma 4")
    parser.add_argument("--suite", action="store_true", help="Run the default benchmark suite once.")
    parser.add_argument("--reliability", action="store_true", help="Run multiple seeded trials.")
    parser.add_argument("--prompt", type=str, help="Run a single ad-hoc prompt.")
    parser.add_argument("--trials", type=int, default=5, help="Number of reliability trials.")
    parser.add_argument("--config-json", type=str, help="Override default config (JSON object string).")
    parser.add_argument("--output", type=str, help="Write JSON results to file instead of stdout.")
    args = parser.parse_args()

    override = {}
    if args.config_json:
        override = json.loads(args.config_json)

    bench = GemmaBenchGPU()

    if args.prompt:
        result = run_prompt(bench, args.prompt, merge_config(override))
        output = json.dumps(result, indent=2)
    elif args.reliability:
        result = run_reliability(bench, override, trials=args.trials)
        output = json.dumps(result, indent=2)
    elif args.suite:
        result = run_suite(bench, override)
        output = json.dumps(result, indent=2)
    else:
        parser.print_help()
        sys.exit(1)

    if args.output:
        with open(args.output, "w") as f:
            f.write(output)
        print(f"Wrote results to {args.output}", file=sys.stderr)
    else:
        print(output)


if __name__ == "__main__":
    main()
